tmforum-oda/oda-canvas

- canvas/charts/controller/values.yaml
Move images from personal repos to tmforumodacanvas repo on Docker Hub
Closes #16
> refactor(chart): move images to tmforumodacanvas

- ReferenceImplementation/cert-manager/install_cert-manager.sh
- canvas/charts/controller/templates/deployment.yaml
- canvas/charts/controller/values.yaml
- canvas/charts/keycloak/Chart.lock
- canvas/charts/keycloak/Chart.yaml
- canvas/charts/webhook/templates/deployment-componentcrdwebhook.yaml
- create_tls_certificates_cert-manager_v1.sh
- install_canvas_cert-manager.sh
Address issue 50 in tmforum-oda/oda-ca and
#24, #25, #26 on tmforum-oda/oda-canvas-charts
closes #24, #25 and #26
> fix(canvas): seccon and cert-manager bugs

- README.md
- canvas/charts/controller/templates/ingressGateway.yaml
- canvas/charts/controller/templates/rbac.yaml
- canvas/charts/controller/values.yaml
- temp.json
Closes #28 
Closes #22 
Also has some minor improvements to the canvas install README
> Canvas on istio

- installation/README.md
- installation/canvas-oda/values.yaml
- installation/cert-manager-init/values.yaml
> 69 instalation istio gateaway falling

- installation/controller/templates/rbac.yaml
- installation/oda-crds/templates/oda-publishednotification-crd.yaml
- installation/oda-crds/templates/oda-subscribednotification-crd.yaml
- source/operators/componentOperator/componentOperator.py
operator: Update the component operator to create publishedNotification & subscribedNotification resources
> Issue #63: publishedNotification & subscribedNotification resources

- installation/canvas-oda/Chart.yaml
- installation/canvas-oda/values.yaml
operator: Fix misspelled words with values.yaml file and Chart.yaml file
Close[ #71](https://github.com/tmforum-oda/oda-canvas/issues/71)
> 73 misspelled words fix

- installation/canvas-oda/README.md
- installation/canvas-oda/values.yaml
> Fix pg parameters

- Canvas-design.md
> Added Canvas design guide

- compliance-test-kit/BDD-and-TDD/features/steps/TDD-implementation-steps.js
> dont validate the TLS certificate

- installation/README.md
> Updated version information in Installation README.md

- compliance-test-kit/BDD-and-TDD/README.md
- compliance-test-kit/BDD-and-TDD/features/UC001-F001-Bootstrap-Apply-Standard-Defined-Role-to-Canvas-Admin-user.feature
Improved the readability for UC001-F001. Relates to issue #85
> Issue85 - improved description

- compliance-test-kit/BDD-and-TDD/features/UC002-F001-Expose-APIs-Create-API-Resource.feature
- compliance-test-kit/BDD-and-TDD/features/UC002-F002-Expose-APIs-Publish-API-Resource-URL.feature
- compliance-test-kit/BDD-and-TDD/features/UC002-F003-Expose-APIs-Verify-API-implementation-is-ready.feature
- installation/oda-crds/templates/oda-component-crd.yaml
- source/operators/README.md
- usecase-library/pumlFiles/bootstrap-role.puml
I've changed the documentation to move from partyRole to permissionSpecificationSet 
contributes to issue #125
> Issue 125 partyrole

- canvas-portal/README.md
- canvas-portal/charts/.helmignore
- canvas-portal/charts/Chart.yaml
- canvas-portal/charts/templates/NOTES.txt
- canvas-portal/charts/templates/_helpers.tpl
- canvas-portal/charts/templates/deployment.yaml
- canvas-portal/charts/templates/ingress.yaml
- canvas-portal/charts/templates/rolebindings.yaml
- canvas-portal/charts/templates/roles.yaml
- canvas-portal/charts/templates/service.yaml
- canvas-portal/charts/templates/serviceaccount.yaml
- canvas-portal/charts/values.yaml
> canvas portal installation

- installation/README.md
- add note about clone git repo
- use triple backticks instead of quadruple backticks
- reformattings
closes #148
> Some small changes and reformattings 

- installation/oda-crds/templates/oda-api-crd.yaml
- installation/oda-crds/templates/oda-component-crd.yaml
- installation/oda-crds/templates/oda-publishednotification-crd.yaml
- installation/oda-crds/templates/oda-subscribednotification-crd.yaml
- source/operators/apiOperatorIstio/apiOperatorIstio.py
- source/operators/componentOperator/componentOperator.py
- source/webhooks/implementation/app.js
Resolves #104 
Fix the webhook, operator and CDRs to support additional attributes
> [v1beta3] Map pub/sub CR fields to component CR

- .gitignore
- installation/oda-crds/templates/oda-component-crd.yaml
- installation/oda-webhook/values.yaml
- source/webhooks/builddockerfile.sh
- source/webhooks/implementation/app.js
> Fixed issue with webhook conversion for v1beta3

- source/utilities/component-viewer/README.md
- source/utilities/component-viewer/index.js
- source/utilities/component-viewer/package-lock.json
- source/utilities/component-viewer/package.json
> 153 utilities upgrade component viewer utility to latest v1beta3 spec version

- .devcontainer/devcontainer.json
- devcontainer.md
definition and description of a dev container for the canvas
close #157
> feat(dev container): Add dev container configuration

- .gitignore
- compliance-test-kit/BDD-and-TDD/README.md
- compliance-test-kit/BDD-and-TDD/identity-manager-utils-keycloak/identity-manager-utils-keycloak.js
- compliance-test-kit/BDD-and-TDD/identity-manager-utils-keycloak/package.json
add possibility to set environment variables in .env file
> provide possibility to set envvars in dotenv file

- .gitignore
- canvas-portal/README.md
- canvas-portal/charts/templates/roles.yaml
- installation/README.md
Merge documentation improvements
Closes #140
> Issue 138 documentation improvements

- charts/oda-crds/templates/oda-exposedapi-crd.yaml
Merging into new feature branch for Exposed API
> First draft of new ExposedAPI resource

- installation/README.md
- installation/precheck.sh
- add precheck shell script
- reformat README
close #184
> Improve install doc

- charts/oda-crds/templates/oda-exposedapi-crd.yaml
> [wip] feat/exposedapi crd

- README.md
- charts/canvas-oda/Chart.yaml
- charts/oda-webhook/Chart.yaml
- charts/oda-webhook/values.yaml
- compliance-test-kit/package.json
- compliance-test-kit/tests.js
- installation/README.md
- source/webhooks/implementation/app.js
> 201 webhook canvas webhook sometimes creates an exposedapispecification with null

- installation/README.md
Ran the CTK against a multi node k3s cluster and everything works out of the box. Installation instructions are just fine.
> Tested with CTK against a multi node k3s cluster

- compliance-test-kit/BDD-and-TDD/testData/productcatalog-static-roles-v1beta3/.helmignore
- compliance-test-kit/BDD-and-TDD/testData/productcatalog-static-roles-v1beta3/Chart.yaml
- compliance-test-kit/BDD-and-TDD/testData/productcatalog-static-roles-v1beta3/templates/component-productcatalog.yaml
- compliance-test-kit/BDD-and-TDD/testData/productcatalog-static-roles-v1beta3/templates/cronjob-productcataloginitialization.yaml
- compliance-test-kit/BDD-and-TDD/testData/productcatalog-static-roles-v1beta3/templates/cronjob-roleinitialization.yaml
- compliance-test-kit/BDD-and-TDD/testData/productcatalog-static-roles-v1beta3/templates/deployment-metricsapi.yaml
- compliance-test-kit/BDD-and-TDD/testData/productcatalog-static-roles-v1beta3/templates/deployment-mongodb.yaml
- compliance-test-kit/BDD-and-TDD/testData/productcatalog-static-roles-v1beta3/templates/deployment-partyroleapi.yaml
- compliance-test-kit/BDD-and-TDD/testData/productcatalog-static-roles-v1beta3/templates/deployment-productcatalogapi.yaml
- compliance-test-kit/BDD-and-TDD/testData/productcatalog-static-roles-v1beta3/templates/persistentVolumeClaim-mongodb.yaml
- compliance-test-kit/BDD-and-TDD/testData/productcatalog-static-roles-v1beta3/templates/service-mongodb.yaml
- compliance-test-kit/BDD-and-TDD/testData/productcatalog-static-roles-v1beta3/templates/service-partyroleapi.yaml
- compliance-test-kit/BDD-and-TDD/testData/productcatalog-static-roles-v1beta3/templates/service-productcatalogapi.yaml
- compliance-test-kit/BDD-and-TDD/testData/productcatalog-static-roles-v1beta3/templates/service-registerallevents.yaml
- compliance-test-kit/BDD-and-TDD/testData/productcatalog-static-roles-v1beta3/values.yaml
> 193 exposing list of roles in component

- feature-definition-and-test-kit/features/UC005-F006-Bootstrap-Creation-Update-Removal-of-Technical-Roles-in-the-Identity-Platform.feature
> Issue#231 - feature creationupdateremoval of corresponding technical roles in the identity platform

- charts/oda-crds/templates/oda-component-crd.yaml
adds the missing secretsManagement structure under securityFunctions.
> #258  Add SecretsManagement section to main component CRD

- source/operators/securityController/README.md
- source/operators/securityController/secconkeycloak.py
- source/operators/securityController/securityControllerKeycloak.py
> Update security controller to add static roles to identity platform

- feature-definition-and-test-kit/features/UC003-F004-Expose-APIs-Upgrade-component-with-additional-API.feature
- feature-definition-and-test-kit/features/step-definition/ComponentManagementSteps.js
- feature-definition-and-test-kit/package-manager-utils-helm/package-manager-utils-helm.js
- feature-definition-and-test-kit/testData/productcatalog-enhanced-v1beta3/templates/component-productcatalog.yaml
- feature-definition-and-test-kit/testData/productcatalog-enhanced-v1beta3/templates/deployment-promotionmanagementapi.yaml
- feature-definition-and-test-kit/testData/productcatalog-enhanced-v1beta3/templates/service-promotionmanagementapi.yaml
- usecase-library/README.md
Closes #271 
Makes helm commands within the feature testing synchronous with `await` and pauses to remove race conditions.
> 271 test component productcatalog enhanced v1beta3

- .github/workflows/check-PR.yml
- .github/workflows/lint-python-code.yml
- charts/canvas-oda/values.yaml
- source/operators/componentOperator/README.md
- source/operators/dependentApiSimpleOperator/docker/README.md
- source/operators/secretsmanagementOperator-hc/docker/README.md
- source/operators/secretsmanagementOperator-hc/sidecar/docker/README.md
- source/operators/securityListener-keycloak/README.md
- source/webhooks/implementation/README.md
simulate PR to master using testmaster.
> ODAA-98: trigger rebuild of all release dockerimages.

- feature-definition-and-test-kit/features/step-definition/ComponentManagementSteps.js
- feature-definition-and-test-kit/resource-inventory-utils-kubernetes/resource-inventory-utils-kubernetes.js
> Added logging of ODA Controller to failed scenarios

- .github/workflows/trigger_tests.yml
Added the github action so tests can be triggered issue #236
> Added the github action so tests can be triggered issue #236

- .github/workflows/dockerbuild-release-secretsmanagement-operator.yml
- charts/canvas-oda/values.yaml
- source/operators/secretsmanagementOperator-hc/docker/README.md
> allow merging to testmaster for testing.

- charts/canvas-oda/Chart.yaml
- charts/oda-webhook/Chart.yaml
- feature-definition-and-test-kit/features/UC002-F001-Install-Component.feature
- feature-definition-and-test-kit/features/UC002-F002-Upgrade-Component.feature
- feature-definition-and-test-kit/features/UC003-F001-Expose-APIs-Create-API-Resource.feature
- feature-definition-and-test-kit/features/UC003-F002-Expose-APIs-Publish-API-Resource-URL.feature
- feature-definition-and-test-kit/features/UC003-F003-Expose-APIs-Verify-API-implementation-is-ready.feature
- feature-definition-and-test-kit/features/UC003-F004-Expose-APIs-Upgrade-component-with-additional-API.feature
- feature-definition-and-test-kit/features/UC003-F005-Expose-APIs-Upgrade-component-with-removed-API.feature
- feature-definition-and-test-kit/features/UC013-F001-Seamless-upgrades-Installing-components-using-prev-version.feature
- feature-definition-and-test-kit/features/UC013-F002-Seamless-upgrades-Canvas-Operators-using-prev-version.feature
- feature-definition-and-test-kit/features/step-definition/APIManagementSteps.js
- feature-definition-and-test-kit/features/step-definition/ComponentManagementSteps.js
- feature-definition-and-test-kit/package-manager-utils-helm/package-manager-utils-helm.js
- feature-definition-and-test-kit/resource-inventory-utils-kubernetes/resource-inventory-utils-kubernetes.js
- feature-definition-and-test-kit/testData/productcatalog-dependendent-API-v1beta3/templates/component-productcatalog.yaml
- feature-definition-and-test-kit/testData/productcatalog-enhanced-v1beta3/templates/component-productcatalog.yaml
- feature-definition-and-test-kit/testData/productcatalog-static-roles-v1beta3/templates/component-productcatalog.yaml
- feature-definition-and-test-kit/testData/productcatalog-updated-v1beta3/templates/component-productcatalog.yaml
- feature-definition-and-test-kit/testData/productcatalog-v1alpha4/templates/component-productcatalog.yaml
- feature-definition-and-test-kit/testData/productcatalog-v1beta1/templates/component-productcatalog.yaml
- feature-definition-and-test-kit/testData/productcatalog-v1beta2/templates/component-productcatalog.yaml
- feature-definition-and-test-kit/testData/productcatalog-v1beta3-sman/templates/component-productcatalog.yaml
- feature-definition-and-test-kit/testData/productcatalog-v1beta3/templates/component-productcatalog.yaml
- feature-definition-and-test-kit/testData/productinventory-v1beta3/templates/component-productcinventory.yaml
- source/webhooks/builddockerfile.sh
- source/webhooks/implementation/app.js
Closes issue #298 
I've tested locally and all tests pass (or are undefined)
> Updated test data apitype to apiType

- charts/canvas-oda/Chart.yaml
Formal release of 1.1.5
@ferenc-hechler, @LesterThomas please can one or the other of you review and merge, then I'll create the release notes.
> Release 1.1.5

- .github/workflows/Combined-Chart-Releaser.yml
added docker image scan feature. this will check all deployments  in canvas namespace and scan all docker images present for security vulnerability.
> Update Combined-Chart-Releaser.yml with docker image scan feature

- charts/canvas-api-gateway/combined-api-gateway-chart/Chart.yaml
- charts/canvas-namespaces/Chart.yaml
- charts/canvas-oda/Chart.yaml
- charts/cert-manager-init/Chart.yaml
> Updated chart versions where appVersion updated to v1beta4

- .github/workflows/dockerbuild-prerelease-secretsmanagement-operator.yml
- .github/workflows/dockerbuild-release-secretsmanagement-operator.yml
- automation/generators/dockerbuild-workflow-generator/dockerbuild-config.yaml
- charts/canvas-oda/Chart.yaml
- charts/canvas-oda/values.yaml
- charts/canvas-vault/templates/post-install-hook.yaml
- charts/secretsmanagement-operator/Chart.yaml
- charts/secretsmanagement-operator/templates/preinst-autodetect-audience-job.yaml
- charts/secretsmanagement-operator/values.yaml
- source/operators/secretsmanagementOperator-hc/docker/Dockerfile
- source/operators/secretsmanagementOperator-hc/docker/README.md
> Issue 378 Support linux/arm docker builds for SecretsManagement

- installation/README.md
Closes #377 
- Added documentation for minimum hardware requirements.
- Corrected section numbers in doc.
> Add minimum hardware requirements

- .github/workflows/dockerbuild-release-api-operator-istio.yml
- .github/workflows/dockerbuild-release-baseimage-kubectl-curl.yml
- .github/workflows/dockerbuild-release-compcrdwebhook.yml
- .github/workflows/dockerbuild-release-component-operator.yml
- .github/workflows/dockerbuild-release-dependentapi-simple-operator.yml
- .github/workflows/dockerbuild-release-secretsmanagement-operator.yml
- .github/workflows/dockerbuild-release-secretsmanagement-sidecar.yml
- .github/workflows/dockerbuild-release-security-listener.yml
- .github/workflows/dockerbuild-release-tmf638-service-inventory-api.yml
- automation/generators/dockerbuild-workflow-generator/templates/dockerbuild-release.yml.jinja2
closes #346 
adding the cosign docker image stage
> Github issue #346 adding the cosign docker image stage

- README.md
- SecurityPrinciples.md
Closes #206 
Add first draft security principles.
> Add first draft security principle and doc links

- charts/canvas-oda/Chart.yaml
> 1.1.8 release

- CONTRIBUTING.md
- charts/code-of-conduct.md
- code-of-conduct.md
Closes #249 
Add code of conduct (based on Contributor Covenant) and contribution guidelines.
> [skip tests] 249 add release contribution and code of conduct

- installation/README.md
corrected values.yaml url in README
> [skip tests] Update README.md

- source/operators/api-management/whalecloud-apim/apiOperatorApig.py
- source/operators/api-management/whalecloud-apim/component-apigController-dockerfile
- source/operators/api-management/whalecloud-apim/component-apigController.yaml
upgrade apig operator from WhaleCloud to v1beta4
> upgrade apig-whalecloud to v1beta4

- source/operators/identity-config/keycloak/identityConfigOperatorKeycloak.py
Added missing startup handler with api server watcher timeout.
> Added watcher configuration on startup of identity operator

- feature-definition-and-test-kit/features/UC002-F003-Install-Component-from-reference-examples.feature
- feature-definition-and-test-kit/features/UC002-F004-Uninstall-Component-from-reference-examples.feature
- feature-definition-and-test-kit/features/step-definition/ComponentManagementSteps.js
- feature-definition-and-test-kit/package-manager-utils-helm/package-manager-utils-helm.js
BDDs for reference examples. Feature testing for installation/uninstallation of components from reference examples repo.
> BDDs for reference examples.

- charts/apisix-gateway/Chart.yaml
- charts/canvas-oda/Chart.yaml
- charts/kong-gateway/Chart.yaml
updated kong and apisix chart names to match with values of oda-canvas chart
> updated kong and apisix chart names

- charts/canvas-oda/Chart.yaml
- charts/canvas-oda/values.yaml
- charts/credentialsmanagement-operator/values.yaml
- charts/identityconfig-operator-keycloak/Chart.yaml
- charts/identityconfig-operator-keycloak/values.yaml
- source/operators/credentials-management/credentialsManagementOperator.py
- source/operators/identity-config/keycloak/identityConfigOperatorKeycloak.py
In this PR updated identityconfig-operator chart to align with the changes made in PR #429 .
> updated identityconfig-operator chart

- charts/canvas-oda/Chart.yaml
- charts/canvas-oda/values.yaml
- charts/identityconfig-operator-keycloak/Chart.yaml
- charts/identityconfig-operator-keycloak/values.yaml
- source/operators/identity-config/keycloak/identity-listener-keycloak-dockerfile
updated keycloak listener dockerfile to remove vulnerabilities
> updated keycloak listener docker image to remove vulnerabilities

- charts/canvas-oda/Chart.yaml
> Release 1.2.2

- usecase-library/pumlFiles/configure-users-and-roles.puml
Updated UC005 puml to clarify clientid and secret
> Update UC005 puml

- charts/apisix-gateway/templates/Deployment.yaml
- charts/apisix-gateway/templates/_helpers.tpl
- charts/apisix-gateway/templates/ingressGatewaywhenApiGatewayenabled.yaml
- charts/apisix-gateway/templates/istio-configMap.yaml
- charts/apisix-gateway/values.yaml
- charts/canvas-oda/values.yaml
- source/operators/api-management/apache-apisix/apiOperatorIstiowithApisix.py
@ferenc-hechler Added required changes for Apisix API Gateway.
> Component multiple namespaces

- source/operators/api-management/apache-apisix/apiOperatorIstiowithApisix.py
- source/operators/api-management/kong/apiOperatorIstiowithKong.py
@ferenc-hechler updated both kong and apisix operators as virtual service was getting created for multiple release with same name.
> updated api gateway operators to restrict vs recreation

- .github/copilot-instructions.md
- ai-coding-assistants.md
- charts/oda-crds/templates/oda-component-crd.yaml
- charts/oda-crds/templates/oda-exposedapi-crd.yaml
- source/operators/api-management/apache-apisix/apiOperatorIstiowithApisix.py
- source/operators/api-management/istio/apiOperatorIstio.py
- source/operators/api-management/kong/apiOperatorIstiowithKong.py
- source/operators/api-management/kong/apiOperatorKong.py
Merging AI Tooling guidance into feature branch
> 487 tools and guidance to use ai coding assistants for developing canvas
